mode:
  production

production:
  datasources:
    mysql:
      host: 127.0.0.1
      port: 3306
      database: spark_jobs
      username: root
      password: mlsql
      initialSize: 8
      removeAbandoned: true
      testWhileIdle: true
      removeAbandonedTimeout: 30
      maxWait: 100
      filters: stat,log4j
      disable: true
    mongodb:
      disable: true
    redis:
      disable: true

test:
  datasources:
    mysql:
      disable: true
    mongodb:
      disable: true

application:
  controllerNames: tech.mlsql.spark.submitter.rest.RestController
  helper:
  service:
  util:
  test:
  static:
    enable: true
  template:
    engine:
      enable: true

serviceframework:
  template:
    loader:
      classpath:
        enable: true
  static:
    loader:
      classpath:
        enable: true
        dir: "streamingpro/assets"
###############http config##################
http:
  disable: false
  port: 9004
thrift:
  disable: true
dubbo:
  disable: true



